import os
import json
import time
from playwright.sync_api import sync_playwright

STATE_FILE = "added_tracks.json"
CHANNEL_URL = "https://www.youtube.com/channel/UCtjpeRS40g7H8oquOSqkB3g/songs"  # Arijit Singh - Topic Songs
BATCH_LIMIT = 50  # Adds 50 songs per run

def load_added_tracks():
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE, "r") as f:
            return set(json.load(f))
    return set()

def save_added_tracks(added_set):
    with open(STATE_FILE, "w") as f:
        json.dump(list(added_set), f, indent=2)

def parse_netscape_cookies(cookies_raw):
    """Parses Netscape cookie strings cleanly into Playwright-compatible dicts."""
    cookies = []
    for line in cookies_raw.splitlines():
        line = line.strip()
        if not line or line.startswith("# "):
            continue

        # Handle #HttpOnly_ lines
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_"):]

        parts = line.split("\t")
        if len(parts) >= 7:
            domain = parts[0].strip()
            # Playwright requires domains to not have leading dots in some protocol versions
            if domain.startswith("."):
                domain = domain[1:]

            cookie_dict = {
                "name": parts[5].strip(),
                "value": parts[6].strip(),
                "domain": domain,
                "path": parts[1].strip() or "/",
                "secure": parts[3].strip().upper() == "TRUE"
            }
            
            # Skip empty or malformed entries
            if cookie_dict["name"] and cookie_dict["value"]:
                cookies.append(cookie_dict)
                
    return cookies

def main():
    playlist_id = os.environ.get("PLAYLIST_ID")
    cookies_raw = os.environ.get("YT_COOKIES")

    if not playlist_id or not cookies_raw:
        print("Error: Missing PLAYLIST_ID or YT_COOKIES environment variables.")
        return

    added_tracks = load_added_tracks()
    cookies = parse_netscape_cookies(cookies_raw)

    print(f"Parsed {len(cookies)} valid cookies.")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(viewport={'width': 1280, 'height': 800})
        
        # Inject cleaned cookies
        context.add_cookies(cookies)
        page = context.new_page()

        print("Navigating to Arijit Singh Topic Songs...")
        page.goto(CHANNEL_URL, wait_until="networkidle")

        # Fetch video URLs
        video_links = page.eval_on_selector_all(
            "a#video-title",
            "elements => elements.map(e => e.href)"
        )

        video_ids = []
        for link in video_links:
            if "watch?v=" in link:
                v_id = link.split("watch?v=")[1].split("&")[0]
                if v_id not in video_ids:
                    video_ids.append(v_id)

        print(f"Total video entries found on channel: {len(video_ids)}")

        pending = [v for v in video_ids if v not in added_tracks]
        print(f"Pending tracks remaining: {len(pending)}")

        if not pending:
            print("All Art Tracks are up to date in playlist!")
            browser.close()
            return

        batch = pending[:BATCH_LIMIT]
        added_count = 0

        for v_id in batch:
            try:
                video_url = f"https://www.youtube.com/watch?v={v_id}"
                print(f"[{added_count + 1}/{len(batch)}] Inspecting video: {v_id}")
                page.goto(video_url, wait_until="networkidle")

                # Double check description to ensure pure Art Track
                description = page.inner_text("ytd-watch-metadata")
                if "Provided to YouTube by" not in description and "Auto-generated by YouTube" not in description:
                    print(f"Skipping {v_id}: Description does not match official Art Track metadata.")
                    continue

                # Trigger Save to playlist popup
                page.click("button[aria-label*='Save to playlist']")
                time.sleep(1.5)

                # Select target playlist
                page.click(f"tp-yt-paper-checkbox:has-text('{playlist_id}')")
                time.sleep(1)

                added_tracks.add(v_id)
                added_count += 1
                print(f"Added {v_id} successfully.")

            except Exception as e:
                print(f"Could not add {v_id}: {e}")
                continue

        save_added_tracks(added_tracks)
        print(f"Run completed. Successfully added {added_count} Art Tracks today.")
        browser.close()

if __name__ == "__main__":
    main()
